# Copyright (C) 2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

name: Generate results page

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - uses: SymbiFlow/actions/checks@main

      - name: Make environment
        run: python3 -m pip install virtualenv && make env

      - name: Check formatting
        run: source .github/workflows/format.sh

      - name: Build HTML
        run: make fetch && make build

      - name: Deploy to GH pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'  }}
        run: |
          cd build
          git init
          cp ../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha  }}"
          git push -u origin +HEAD:gh-pages
          rm -rf .git
